# This docker-compose requires host networking, which is only available on Linux
# This compose will not function correctly on Mac or Windows
services:
  caddy:
    image: livekit/caddyl4
    command: run --config /etc/caddy.yaml --adapter yaml
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./caddy.yaml:/etc/caddy.yaml:ro
      - ./caddy_data:/data
  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - redis_data:/data
    sysctls:
      - net.core.somaxconn=65535
    deploy:
      resources:
        limits:
          memory: 512M
  egress:
    image: livekit/egress:latest
    command: --config /etc/egress.yaml
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./egress.yaml:/etc/egress.yaml:ro
    cap_add:
      - CAP_SYS_ADMIN
  ingress:
    image: livekit/ingress:latest
    command: --config /etc/ingress.yaml
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./ingress.yaml:/etc/ingress.yaml:ro

volumes:
  redis_data:
