# This docker-compose requires host networking, which is only available on Linux
# This compose will not function correctly on Mac or Windows
services:
  caddy:
    image: livekit/caddyl4
    restart: unless-stopped
    network_mode: "host"
    environment:
      - CADDY_CONFIG_FILE=/etc/caddy.yaml
    volumes:
      - ./caddy.yaml:/etc/caddy.yaml
      - caddy_data:/data
  livekit:
    image: livekit/livekit-server:latest
    restart: unless-stopped
    network_mode: "host"
    environment:
      - LIVEKIT_CONFIG_FILE=/etc/livekit.yaml
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 512M
  egress:
    image: livekit/egress:latest
    restart: unless-stopped
    network_mode: "host"
    environment:
      - EGRESS_CONFIG_FILE=/etc/egress.yaml
    volumes:
      - ./egress.yaml:/etc/egress.yaml
    cap_add:
      - CAP_SYS_ADMIN
  ingress:
    image: livekit/ingress:latest
    restart: unless-stopped
    network_mode: "host"
    environment:
      - INGRESS_CONFIG_FILE=/etc/ingress.yaml
    volumes:
      - ./ingress.yaml:/etc/ingress.yaml

volumes:
  redis_data:
  caddy_data:
